name: high_chart
description: A chart library based on High Charts (.JS), able to build advanced
  charts like Pie chart, linear chart, etc.
version: 2.1.0
homepage: https://gitee.com/yotaicloud/high_chart

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.5
  url_launcher: ^6.1.0
  webview_flutter: ^4.2.0
  webview_flutter_android: ^3.7.0
  webview_flutter_wkwebview: ^3.4.3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.senthilnasa.high_chart
        pluginClass: HighChartPlugin
      ios:
        pluginClass: HighChartPlugin
      web:
        pluginClass: HighChartPlatformInterface
        fileName: high_chart_web.dart
